name: CI/CD Pipeline

on:
  # Temporarily disabling automatic triggers.
  # Uncomment the lines below to re-enable push and pull_request triggers.
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Run tests
        run: pytest tests/

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with AWS SAM
        run: |
          pip install aws-sam-cli
          sam deploy --region us-east-1 --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name fintech-payments-sim --capabilities CAPABILITY_IAM

  zap_scan:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://b5klyi27g5.execute-api.us-east-1.amazonaws.com/Prod/pay'

      - name: Check for vulnerabilities
        run: |
          if grep -q "FAIL-NEW" owasp-zap-report.txt; then
            echo "Vulnerabilities found! Failing build."
            exit 1
          fi
